/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package examen1_jorgezuniga;

import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alejandro
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        DefaultComboBoxModel modelo
                = (DefaultComboBoxModel) tipodecampista.getModel();
        modelo.addElement("Campista");
        modelo.addElement("El machetero");

        tipodecampista.setModel(modelo);

        DefaultComboBoxModel modelo1
                = (DefaultComboBoxModel) tipoArma.getModel();
        modelo1.addElement("Hacha");
        modelo1.addElement("Pistola");
        modelo1.addElement("Bate");
        modelo1.addElement("Pala");
        modelo1.addElement("Sierra electrica");
        modelo1.addElement("Putasos");
        tipoArma.setModel(modelo1);

        DefaultComboBoxModel modelo2
                = (DefaultComboBoxModel) Sexo.getModel();
        modelo2.addElement("Femenino");
        modelo2.addElement("Masculino");
        Sexo.setModel(modelo2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupobotones = new javax.swing.ButtonGroup();
        pestanas = new javax.swing.JTabbedPane();
        crear = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tipodecampista = new javax.swing.JComboBox<>();
        Edad = new javax.swing.JFormattedTextField();
        Nombre = new javax.swing.JTextField();
        tipoArma = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Guardar = new javax.swing.JButton();
        Sexo = new javax.swing.JComboBox<>();
        editar = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        NombreModi = new javax.swing.JTextField();
        EdadModi = new javax.swing.JFormattedTextField();
        rb_fModi = new javax.swing.JRadioButton();
        rb_mModi = new javax.swing.JRadioButton();
        tipoArmaModi = new javax.swing.JComboBox<>();
        Modificar = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        tipodecampistaModi1 = new javax.swing.JComboBox<>();
        Lista1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        eliminar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        Posicion = new javax.swing.JFormattedTextField();
        Lista3 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        Eliminar = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        enlistar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Lista2 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        Lista4 = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pestanas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                pestanasStateChanged(evt);
            }
        });

        crear.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Edad");
        crear.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 142, 63, 24));

        jLabel2.setBackground(new java.awt.Color(255, 0, 0));
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("Nombre ");
        crear.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 75, 63, 24));

        jLabel3.setBackground(new java.awt.Color(255, 0, 0));
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Sexo");
        crear.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 63, 24));

        jLabel4.setBackground(new java.awt.Color(255, 0, 0));
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Arma");
        crear.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 63, 24));

        jLabel5.setBackground(new java.awt.Color(255, 0, 0));
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Tipo");
        crear.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 63, 24));

        tipodecampista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipodecampistaActionPerformed(evt);
            }
        });
        crear.add(tipodecampista, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 82, -1));

        try {
            Edad.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        crear.add(Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 145, 82, -1));
        crear.add(Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 78, 82, -1));

        tipoArma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoArmaActionPerformed(evt);
            }
        });
        crear.add(tipoArma, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 204, -1));

        jLabel6.setBackground(new java.awt.Color(255, 0, 0));
        jLabel6.setFont(new java.awt.Font("Ebrima", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 204));
        jLabel6.setText("Nuevo Campista?");
        crear.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(208, 12, 309, 41));

        Guardar.setForeground(new java.awt.Color(255, 0, 0));
        Guardar.setText("Guardar");
        Guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GuardarMouseClicked(evt);
            }
        });
        Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActionPerformed(evt);
            }
        });
        crear.add(Guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 133, 69));

        crear.add(Sexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 80, -1));

        pestanas.addTab("Crear Persona", null, crear, "");

        editar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 0, 0));
        jLabel7.setForeground(new java.awt.Color(51, 204, 0));
        jLabel7.setText("Nombre ");
        jLabel7.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 204)));
        editar.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, 50));

        jLabel8.setBackground(new java.awt.Color(255, 0, 0));
        jLabel8.setForeground(new java.awt.Color(51, 204, 0));
        jLabel8.setText("Edad");
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 204)));
        editar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, -1, 50));

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setForeground(new java.awt.Color(51, 204, 0));
        jLabel9.setText("Sexo");
        jLabel9.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 204)));
        editar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, 50));

        jLabel10.setBackground(new java.awt.Color(255, 0, 0));
        jLabel10.setForeground(new java.awt.Color(51, 204, 0));
        jLabel10.setText("Tipo");
        jLabel10.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 204)));
        editar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, 50));

        jLabel11.setBackground(new java.awt.Color(255, 0, 0));
        jLabel11.setForeground(new java.awt.Color(51, 204, 0));
        jLabel11.setText("Arma");
        jLabel11.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 204)));
        editar.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, -1, 50));
        editar.add(NombreModi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 160, 30));

        try {
            EdadModi.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        EdadModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EdadModiActionPerformed(evt);
            }
        });
        editar.add(EdadModi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 160, 30));

        rb_fModi.setText("F");
        rb_fModi.setToolTipText("");
        rb_fModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_fModiActionPerformed(evt);
            }
        });
        editar.add(rb_fModi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        rb_mModi.setSelected(true);
        rb_mModi.setText("M");
        rb_mModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb_mModiActionPerformed(evt);
            }
        });
        editar.add(rb_mModi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        tipoArmaModi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipoArmaModiActionPerformed(evt);
            }
        });
        editar.add(tipoArmaModi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, 160, -1));

        Modificar.setForeground(new java.awt.Color(0, 204, 0));
        Modificar.setText("Modificar");
        Modificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarMouseClicked(evt);
            }
        });
        editar.add(Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 170, 80));

        jLabel12.setBackground(new java.awt.Color(255, 0, 0));
        jLabel12.setFont(new java.awt.Font("Ebrima", 3, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 255, 0));
        jLabel12.setText("Editar");
        editar.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 130, -1));

        tipodecampistaModi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tipodecampistaModi1ActionPerformed(evt);
            }
        });
        editar.add(tipodecampistaModi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 160, -1));

        Lista1.setForeground(new java.awt.Color(0, 204, 204));
        editar.add(Lista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 340, 30));

        jLabel17.setBackground(new java.awt.Color(255, 0, 0));
        jLabel17.setForeground(new java.awt.Color(51, 204, 0));
        jLabel17.setText("personas");
        jLabel17.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 204)));
        editar.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, 110, 50));

        pestanas.addTab("Editar Persona", editar);

        eliminar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setBackground(new java.awt.Color(255, 0, 0));
        jLabel13.setFont(new java.awt.Font("Ebrima", 3, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 255, 0));
        jLabel13.setText("Eliminar");
        eliminar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 160, -1));

        try {
            Posicion.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Posicion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PosicionActionPerformed(evt);
            }
        });
        eliminar.add(Posicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 120, 40));

        Lista3.setForeground(new java.awt.Color(0, 204, 204));
        eliminar.add(Lista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 330, 40));

        jLabel18.setBackground(new java.awt.Color(255, 0, 0));
        jLabel18.setForeground(new java.awt.Color(51, 204, 0));
        jLabel18.setText("Posicion que desea eliminar");
        jLabel18.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 204)));
        eliminar.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 50));

        Eliminar.setForeground(new java.awt.Color(0, 204, 0));
        Eliminar.setText("Eliminar");
        Eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarMouseClicked(evt);
            }
        });
        eliminar.add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 310, 170, 80));

        jLabel19.setBackground(new java.awt.Color(255, 0, 0));
        jLabel19.setForeground(new java.awt.Color(51, 204, 0));
        jLabel19.setText("campistas");
        jLabel19.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 204)));
        eliminar.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 130, 50));

        pestanas.addTab("Eliminar", eliminar);

        enlistar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setBackground(new java.awt.Color(255, 0, 0));
        jLabel14.setFont(new java.awt.Font("Ebrima", 3, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 255, 0));
        jLabel14.setText("Enlistar");
        enlistar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 140, -1));

        Lista2.setForeground(new java.awt.Color(0, 204, 204));
        enlistar.add(Lista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 460, 40));

        jLabel16.setBackground(new java.awt.Color(255, 0, 0));
        jLabel16.setForeground(new java.awt.Color(51, 204, 0));
        jLabel16.setText("Los macheteros");
        jLabel16.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 204)));
        enlistar.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 130, 50));

        Lista4.setForeground(new java.awt.Color(0, 204, 204));
        enlistar.add(Lista4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 460, 40));

        jLabel20.setBackground(new java.awt.Color(255, 0, 0));
        jLabel20.setForeground(new java.awt.Color(51, 204, 0));
        jLabel20.setText("campistas");
        jLabel20.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 204)));
        enlistar.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 130, 40));

        pestanas.addTab("Enlistar", enlistar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pestanas)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pestanas, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tipoArmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoArmaActionPerformed

    }//GEN-LAST:event_tipoArmaActionPerformed

    private void tipodecampistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipodecampistaActionPerformed

    }//GEN-LAST:event_tipodecampistaActionPerformed

    private void pestanasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_pestanasStateChanged
        //cambio de pestana

    }//GEN-LAST:event_pestanasStateChanged

    private void GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GuardarActionPerformed

    private void GuardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GuardarMouseClicked
        // guardar
        int edad, danoarma = 0;
        String nombre, sexo = "", tipocampista, nombrearma;
        try {
            nombre = Nombre.getText();
            edad = Integer.parseInt(Edad.getText());
            if (Sexo.getSelectedItem() == "Masculino") {
                sexo = "Masculino";
            }
            if (Sexo.getSelectedItem() == "Femenino") {
                sexo = "Femenino";
            }
//            idioma = cb_idioma.getSelectedItem().toString();

            nombrearma = tipoArma.getSelectedItem().toString();
            if (tipoArma.getSelectedItem() == "Hacha") {
                danoarma = 80;
            }
            if (tipoArma.getSelectedItem() == "Pistola") {
                danoarma = 86;
            }
            if (tipoArma.getSelectedItem() == "Bate") {
                danoarma = 75;
            }
            if (tipoArma.getSelectedItem() == "Pala") {
                danoarma = 78;
            }
            if (tipoArma.getSelectedItem() == "Sierra electrica") {
                danoarma = 100;
            }
            if (tipoArma.getSelectedItem() == "Putasos") {
                danoarma = 60;
            }
            tipocampista = tipodecampista.getSelectedItem().toString();
            arma.add(new Armas(nombrearma, danoarma));
            if ("Campista".equals(tipocampista)) {
                Personas cap =  new Personas(nombre, "Campista", sexo, edad, arma);
                Campistas.add(cap);
                DefaultComboBoxModel dc = (DefaultComboBoxModel) Lista2.getModel();
                dc.addElement(cap);
                Lista2.setModel(dc);
            }
            if ("El machetero".equals(tipocampista)) {
                Personas mach =  new Personas(nombre, "El machetero", sexo, edad, arma);
                machete.add(mach);
                DefaultComboBoxModel xx = (DefaultComboBoxModel) Lista4.getModel();
                xx.addElement(mach);
                Lista4.setModel(xx);
            }

            Personas x = new Personas(nombre, tipocampista, sexo, edad, arma);
            personas.add(x);
            DefaultComboBoxModel pp = (DefaultComboBoxModel) Lista1.getModel();
            pp.addElement(x);
            Lista1.setModel(pp);
            DefaultComboBoxModel yy = (DefaultComboBoxModel) Lista3.getModel();
            yy.addElement(x);
            Lista2.setModel(yy);

            arma.remove(0);
            Nombre.setText("");
            Edad.setText("");
            Sexo.setSelectedItem(null);
            tipodecampista.setSelectedItem(null);
            tipoArma.setSelectedItem(null);
            JOptionPane.showMessageDialog(null, "Guardado exitosamente!!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error!!");
        }


    }//GEN-LAST:event_GuardarMouseClicked

    private void rb_fModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_fModiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_fModiActionPerformed

    private void rb_mModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb_mModiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb_mModiActionPerformed

    private void tipoArmaModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipoArmaModiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipoArmaModiActionPerformed

    private void ModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarMouseClicked
        
//modificar
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_ModificarMouseClicked

    private void tipodecampistaModi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tipodecampistaModi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tipodecampistaModi1ActionPerformed

    private void EdadModiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EdadModiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EdadModiActionPerformed

    private void PosicionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PosicionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PosicionActionPerformed

    private void EliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarMouseClicked
        // Eliminar
        personas.remove(Integer.parseInt(Posicion.getText()));
        JOptionPane.showMessageDialog(this, "La persona se elimino correctamente!!");
        
        
    }//GEN-LAST:event_EliminarMouseClicked
    public void guardar() {
        int edad;
        String nombre, sexo, tipocampista, tipoarma;
    }

    public void Lista1() {
        for (Object t : personas) {

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField Edad;
    private javax.swing.JFormattedTextField EdadModi;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Guardar;
    private javax.swing.JComboBox<String> Lista1;
    private javax.swing.JComboBox<String> Lista2;
    private javax.swing.JComboBox<String> Lista3;
    private javax.swing.JComboBox<String> Lista4;
    private javax.swing.JButton Modificar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JTextField NombreModi;
    private javax.swing.JFormattedTextField Posicion;
    private javax.swing.JComboBox<String> Sexo;
    private javax.swing.JPanel crear;
    private javax.swing.JPanel editar;
    private javax.swing.JPanel eliminar;
    private javax.swing.JPanel enlistar;
    private javax.swing.ButtonGroup grupobotones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane pestanas;
    private javax.swing.JRadioButton rb_fModi;
    private javax.swing.JRadioButton rb_mModi;
    private javax.swing.JComboBox<String> tipoArma;
    private javax.swing.JComboBox<String> tipoArmaModi;
    private javax.swing.JComboBox<String> tipodecampista;
    private javax.swing.JComboBox<String> tipodecampistaModi1;
    // End of variables declaration//GEN-END:variables
    ArrayList personas = new ArrayList();
    ArrayList machete = new ArrayList();
    ArrayList Campistas = new ArrayList();
    ArrayList<Armas> arma = new ArrayList();
    int flag = 0;
}
